### ISSUE TITLE
User sign up 修正点

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#10]
# 修正点

kibela
https://doc-inc.kibe.la/shared/entries/dd86de7e-6cab-4fc9-8881-6c5054f38d86

全体的に、デザインの細かいところが再現されていません。
inspectモードでサイズ感など確認できるので、しっかり確認してからコーディングするようにしてください。
https://projects.invisionapp.com/d/main#/console/16945593/351288227/inspect

## コーディング・デザイン
・mobile対応になっていない
・shadowがデザインと違う。
![スクリーンショット 2019-03-26 14 54 17](https://user-images.githubusercontent.com/22842524/54974337-11667100-4fd7-11e9-96d1-e4ae5422d18f.png)
![スクリーンショット 2019-03-26 14 54 21](https://user-images.githubusercontent.com/22842524/54974338-11ff0780-4fd7-11e9-8fce-8d612ba2f7d2.png)
・headerがデザインと違う
・利用規約がデザインと違う
【正】
![スクリーンショット 2019-03-26 15 30 07](https://user-images.githubusercontent.com/22842524/54976029-648ef280-4fdc-11e9-8c37-65753d09527c.png)
・errorメッセージがデザインと違う
![スクリーンショット 2019-03-26 16 24 21](https://user-images.githubusercontent.com/22842524/54978423-af603880-4fe3-11e9-842d-88dd7e43be7f.png)
![スクリーンショット 2019-03-26 16 33 06](https://user-images.githubusercontent.com/22842524/54978864-dbc88480-4fe4-11e9-90cf-301249c9b060.png)
https://projects.invisionapp.com/d/main#/console/16945593/351288222/inspect
・form間の幅。デザインでは、24px間隔です。
![スクリーンショット 2019-03-26 16 31 12](https://user-images.githubusercontent.com/22842524/54978785-a3c14180-4fe4-11e9-9d62-9485a79a6ae3.png)
![スクリーンショット 2019-03-26 16 30 16](https://user-images.githubusercontent.com/22842524/54978734-85f3dc80-4fe4-11e9-9819-19a1cadc9193.png)
・formのサイズが違う
→heightは46pxです。
・会員登録(無料)とformの距離が近い
![スクリーンショット 2019-03-26 15 21 48](https://user-images.githubusercontent.com/22842524/54975599-eed65700-4fda-11e9-8f38-864d37df9151.png)
![スクリーンショット 2019-03-26 15 21 56](https://user-images.githubusercontent.com/22842524/54975600-ef6eed80-4fda-11e9-9a6e-bd4321eb8f03.png)
・余計なfont-weightが入っている
![スクリーンショット 2019-03-26 16 22 22](https://user-images.githubusercontent.com/22842524/54978325-5bedea80-4fe3-11e9-839e-a5dbb4650e8e.png)
・footerが違う
![スクリーンショット 2019-03-26 16 23 01](https://user-images.githubusercontent.com/22842524/54978352-73c56e80-4fe3-11e9-8041-5717c75ff5a3.png)

・間隔がデザイン通りではない
![スクリーンショット 2019-03-26 17 08 04](https://user-images.githubusercontent.com/22842524/54980723-d883c780-4fe9-11e9-9344-edbc14bcee94.png)

## 機能
・姓名
```
全角以外だったらフォーカスアウト時に項目直下にアラート表示
→「名前(姓)を正しく入力してください」
```
→満たしていない

・電話番号
全角だったら半角に置き換え
→満たしていない

ハイフンついていたら外す
→満たしていない

・email
```
フォーカスアウト時にフリーアドレスだったらアラート表示
→「フリーメールアドレスでの登録はご遠慮頂いております」
```
→満たしていない

```
下に注意文

＊こちらに入力されたメールアドレスに資料ダウンロードURLが送られます。
＊フリーメールアドレスでの登録はご遠慮頂いております。
```
→満たしていない

・password
```
※ 設定したパスワードで当サイトにログインすると、資料をダウンロードすることができます。
```
→満たしていない

・初期値は `選択してください`
![スクリーンショット 2019-03-26 16 46 35](https://user-images.githubusercontent.com/22842524/54979579-d9672a00-4fe6-11e9-9bf0-975a4bc1e2cb.png)
![スクリーンショット 2019-03-26 16 47 40](https://user-images.githubusercontent.com/22842524/54979597-e6841900-4fe6-11e9-918d-8c886df1fd02.png)

・利用規約
プライバシーポリシー、利用規約それぞれにリンクを貼る
→満たしていない

利用規約に同意していないのに、無料登録できてしまう
![スクリーンショット 2019-03-26 16 49 59](https://user-images.githubusercontent.com/22842524/54979721-395dd080-4fe7-11e9-9017-588aeaa7df54.png)

**Comment by ericgpks** [comment]
If the content is empty then show alert and change the color to red.
After that, fill the container with the correct style, then please get back this color to normal.
![image](https://user-images.githubusercontent.com/40660382/55598718-2a1d1680-578f-11e9-958c-5de758253ad4.png)

**Comment by ericgpks** [comment]
The authentication mail is sent like this. Please fix it.
![image](https://user-images.githubusercontent.com/40660382/55599028-bbd95380-5790-11e9-8451-1f1df15ed61b.png)
