### ISSUE TITLE
User sign upができない

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#11]
# 背景
Userのsign upをしようと思ったら、エラーが発生した。
[![Image from Gyazo](https://i.gyazo.com/e7a1a5df8e94d60a650bc2c5fd03bf37.gif)](https://gyazo.com/e7a1a5df8e94d60a650bc2c5fd03bf37)

# 再現手順
/users/sign_up
にて、全ての情報を埋めたのちに、`無料で会員登録` を押したらエラーが発生。

**Comment by reiji11011** [comment]
![スクリーンショット 2019-03-26 17 11 23](https://user-images.githubusercontent.com/22842524/54980851-344e5080-4fea-11e9-9f65-b71cb5e855bb.png)

**Comment by ericgpks** [comment]
・In spite of filling all contents, I can't sign up and then I can't click submit bottom anymore.
[![Image from Gyazo](https://i.gyazo.com/dc1d155f9e85a187a02acdb51699300c.gif)](https://gyazo.com/dc1d155f9e85a187a02acdb51699300c)

**Comment by hugh-n** [comment]
OK

It should be possible to register with current develop branch.
