### ISSUE TITLE
User Password Forget 修正点

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#13]
## デザイン

・文言
```
へご登録のメールアドレスをご入力ください。
パスワード再発行手続きのメールを送りします。
```

![スクリーンショット 2019-03-26 17 50 33](https://user-images.githubusercontent.com/22842524/54983203-ad9c7200-4fef-11e9-8e37-8870675b17c9.png)

・formの間隔
![スクリーンショット 2019-03-26 17 50 46](https://user-images.githubusercontent.com/22842524/54983232-b8ef9d80-4fef-11e9-88a5-0550a71eb380.png)

・formとfooterとheaderとの間隔
![スクリーンショット 2019-03-26 17 51 10](https://user-images.githubusercontent.com/22842524/54983264-ca38aa00-4fef-11e9-9b69-bc8382355fcf.png)

・displayにて、footerが浮く
![スクリーンショット 2019-03-26 17 51 34](https://user-images.githubusercontent.com/22842524/54983287-d45aa880-4fef-11e9-8d8f-6047653b1de9.png)

**Comment by hugh-n** [comment]
Footer part is not yet fixed.
