### ISSUE TITLE
header 修正点

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#14]
kibela 
https://doc-inc.kibe.la/shared/entries/3c3ba2d9-94ec-4860-9102-44da72d271b0

invision
https://projects.invisionapp.com/d/main#/console/16945593/351911561/preview

【現状】
![スクリーンショット 2019-03-26 18 09 02](https://user-images.githubusercontent.com/22842524/54984502-51871d00-4ff2-11e9-8213-64867249e167.png)
【正】
![スクリーンショット 2019-03-26 18 11 23](https://user-images.githubusercontent.com/22842524/54984634-9dd25d00-4ff2-11e9-9e9d-2e8ae4eda259.png)

・`はじめての方へ` の動線がない

・ボタン
・要素間の間隔
などを、デザインを見て合わせてほしい
![スクリーンショット 2019-03-26 18 10 38](https://user-images.githubusercontent.com/22842524/54984581-7c717100-4ff2-11e9-9523-001866d62363.png)

・各リンクへ遷移を行う
→満たしていない

・dnusのロゴを押すと、rootに戻る(https://dnus.jp)
→満たしていない

・白線の区切り線がない
![スクリーンショット 2019-03-26 18 14 53](https://user-images.githubusercontent.com/22842524/54984893-29e48480-4ff3-11e9-97c4-3017d4dee603.png)

**Comment by hugh-n** [comment]
Fixed.

This should be ok  now in current develop branch.
