### ISSUE TITLE
Home 修正点

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#15]
kibela 
https://doc-inc.kibe.la/shared/entries/89e42473-ead1-4a9c-930d-b86f562719ea

invision
https://projects.invisionapp.com/d/main#/console/16945593/351870582/comments/112322675

・矢印がついていない
![スクリーンショット 2019-03-26 18 28 14](https://user-images.githubusercontent.com/22842524/54985863-fd316c80-4ff4-11e9-9d31-6c0a70f80abf.png)

・ここが全てlinkになる
![スクリーンショット 2019-03-26 18 29 42](https://user-images.githubusercontent.com/22842524/54985984-29e58400-4ff5-11e9-8988-6b766f6874d9.png)

・fontawsomeが入っていない

人材サービス
賃貸/ 住宅
https://fontawesome.com/icons/home?style=solid

通信/ SIM
https://fontawesome.com/icons/signal?style=solid

ビザ/ 士業
https://fontawesome.com/icons/passport?style=solid

教育/ 日本語
https://fontawesome.com/icons/school?style=solid

翻訳/ 通訳
https://fontawesome.com/icons/language?style=solid

外国人受け入れサポート
https://fontawesome.com/icons/handshake-alt?style=solid

その他
https://fontawesome.com/icons/users?style=solid

**Comment by andybit-okutama** [comment]
人材サービス
https://fontawesome.com/icons/users?style=solid

賃貸/ 住宅
https://fontawesome.com/icons/home?style=solid

通信/ SIM
https://fontawesome.com/icons/signal?style=solid

ビザ/ 士業
https://fontawesome.com/icons/passport?style=solid

教育/ 日本語
https://fontawesome.com/icons/school?style=solid

翻訳/ 通訳
https://fontawesome.com/icons/language?style=solid

外国人受け入れサポート
https://fontawesome.com/icons/hands-helping?style=solid

その他
https://fontawesome.com/icons/file?style=solid

**Comment by andybit-okutama** [comment]
i follow this

**Comment by andybit-okutama** [comment]
![Home](https://user-images.githubusercontent.com/34153533/55042516-2eea1800-5075-11e9-8d22-0232899d5281.gif)

**Comment by reiji11011** [comment]
>i follow this https://doc-inc.kibe.la/shared/entries/2c1d8943-f404-4811-8bce-12ba49410371

It's OK

**Comment by ericgpks** [comment]
![スクリーンショット (748)](https://user-images.githubusercontent.com/40660382/55774421-02e88100-5ad0-11e9-8e23-8df993ab6f8b.png)

In this article area, the image isn't shown all in spite of having a space for the image.
