### ISSUE TITLE
カテゴリーページのデザイン

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#16]
デザインをみて、大きさ、幅等の調整をお願いします
URL
http://localhost:3000/recruitment

kibela
https://doc-inc.kibe.la/shared/entries/7c91fc32-5415-42bd-bbf7-a314161624e0

invision
https://projects.invisionapp.com/d/main#/console/16945593/352023869/preview

**Comment by andybit-okutama** [comment]
![Design Service new](https://user-images.githubusercontent.com/34153533/55042326-4e347580-5074-11e9-99bc-bf1d0341da93.gif)

it this correct
