### ISSUE TITLE
admin/sign_in にて、basic認証機能がない

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#20]
# 概要
```
`https://dnus.jp/admins/sign_in` のURLに、本番環境でのみ、Basic認証をかける
Basic認証の内容は
`
ID：doc
pass：duns
`
で生成してください。
```

の要件が実装されていませんでした。
https://doc-inc.kibe.la/shared/entries/a4aec9b9-a4e3-4902-ab51-66a07ab4a095

# 確認したこと
・admin/session_controller.rb を確認したがなし
・application/controller.rb を確認したがなし
・[basic]というキーワードで検索したがなし
・[dnus]というキーワードで検索したがなし

もし実装していたらごめんなさいm(_ _)m

**Comment by hugh-n** [comment]
Fixed.

Basic認証は追加されました。
