### ISSUE TITLE
admin/companies/new の住所とplaceholderが一致していない

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#21]
現状
![スクリーンショット 2019-04-02 11 31 15](https://user-images.githubusercontent.com/22842524/55371957-f9dd3a00-553a-11e9-97e1-2a0bbd8c3390.png)

見本
https://projects.invisionapp.com/d/main#/console/16945593/352585010/preview

**Comment by hugh-n** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/34264567/56018429-14829080-5d3d-11e9-8b64-0107cbfaf6a9.png)
