### ISSUE TITLE
User Business Mail

### ISSUE THREAD

**Issue by ericgpks** [andybit-okutama/doc-dnus#34]
The content of the mail is different from the requirement.
https://doc-inc.kibe.la/shared/entries/491888f4-7eb4-4b23-9ec0-4544d01d9d86
Please check it.
![image](https://user-images.githubusercontent.com/40660382/55798840-de5dca80-5b0a-11e9-9c97-45c51c1d1cce.png)

**Comment by andybit-okutama** [comment]
It fix
