### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by hugh-n** [andybit-okutama/doc-dnus#44]
**Footer**

![Footer](https://user-images.githubusercontent.com/34264567/56046140-91cdf580-5d7d-11e9-88e3-7bfab031b52a.png)
Space below footer if height of page is small.

----------

**Home**

![Home   Category](https://user-images.githubusercontent.com/34264567/56046169-9c888a80-5d7d-11e9-86ea-6100f1180a6b.png)
Home Page: 「＞」 not link

---------

**MyPage**

![MyPage](https://user-images.githubusercontent.com/34264567/56046181-a611f280-5d7d-11e9-9a2c-5a38ca2c2c0d.png)
MyPage Contents size does not match if screen width is too large

--------

**Service**

![Disabled Checkbox](https://user-images.githubusercontent.com/34264567/56046211-b629d200-5d7d-11e9-8bcc-2734de74c347.png)
Text located above checkbox missing

----------

**Password Forgot**

![Reset Password](https://user-images.githubusercontent.com/34264567/56046508-6b5c8a00-5d7e-11e9-99c7-becb44cb496c.png)
Password Edit Page (確認必要)
If trigger error when trying to change password (blank input, less than 8 characters, password and password confirmation not the same), the token breaks and doesn't seem to work anymore.

I was only able to fix it by sending new token. Copy and pasting previous token doesn't seem to work.

**Comment by ericgpks** [comment]
User SignIn
登録のないパスワードが入力されたときに「無効なパスワードです」が表示されること
