### ISSUE TITLE
新規会員登録のデザインとhover時の挙動

### ISSUE THREAD

**Issue by reiji11011** [andybit-okutama/doc-dnus#9]
# 修正点
・デザインがモックとやや違う
・hover時の挙動が違う

完成予想図
[![Image from Gyazo](https://i.gyazo.com/350e78bdcf7c2c76eae48afb834d7dad.gif)](https://gyazo.com/350e78bdcf7c2c76eae48afb834d7dad)

**Comment by andybit-okutama** [comment]
![shadow button](https://user-images.githubusercontent.com/34153533/55042455-df0b5100-5074-11e9-93f5-ca2786f6bca8.gif)

is this shadow hove correct

**Comment by reiji11011** [comment]
It's doesn`t same.
check it.
https://boxil.jp/
